ZZRGNDUT
 I $T(EN^XTMUNIT)'="" D EN^XTMUNIT("ZZRGNDUT")
 Q
 ;
PKGUTIL
 N PKG
 S PKGSPATH="D:\"
 D READPKGS^ZZRGND19("^ZZRGT",1)
 S PKG=$$GETPKG^ZZRGND19("ZUGTM","^ZZRGT")
 D CHKEQ^XTMUNIT("XU",PKG,"$$GETPKG^ZZRGND19: Wrong namespace for GMPLSAVE routine.")
 S PKG=$$GPKGNAME^ZZRGND19(PKG,"^ZZRGT")
 D CHKEQ^XTMUNIT("KERNEL",PKG,"$$GPKGNAME^ZZRGND19: Wrong package name for ZUGTM routine.")
 Q
 ;
NDXFMAN
 N RESULT
 D NDXFMAN^ZZRGND17("^ZZRG","BPSUSCR2","COLACTRQ",.RESULT,0) 
 ;COLACTRQ
 ; ...
 ; S TFILE=9002313.59,CFILE=9002313.02
 ; ...
 ; .. S LSTUDT=$$GET1^DIQ(TFILE,IEN59,7,"I")
 D:$D(RESULT)<10 FAIL^XTMUNIT("NDXFMAN - RESULT empty") Q
 D:$D(RESULT("FMG")) FAIL^XTMUNIT("NDXFMAN - No FileMan globals in RESULT") Q
 D:$D(RESULT("FMGC")) FAIL^XTMUNIT("NDXFMAN - No FileMan calls in RESULT") Q
 D CHKEQ^XTMUNIT(1,$D(RESULT("FMG","^BPSC(")),"Missing ^BPSC")
 D CHKEQ^XTMUNIT(1,$D(RESULT("FMG","^BPST(")),"Missing ^BPST")
 D CHKEQ^XTMUNIT(1,$D(RESULT("FMGC","$$GET1^DIQ")),"Missing $$GET1^DIQ call")
 Q
 ;
XTENT
 ;;PKGUTIL
 ;;NDXFMAN
 Q
 ;