ZZRGND14 ;
 ;;
 Q  ; USE TAGS
 ;
NEWINP(INP) ;
 N I
 F I=1:1:10 S INP(I)=0
 S INP(11)=""  ; Package
 S INP(12)=""  ; Build
 S INP("MAX")=20000  ;Max routine size
 S INP("CMAX")=15000 ;Max Code in routine
 Q  
 ;
CRTBASE(GLB) ;
 N CNT,RTN,INP,NRO,DA,INDDA 
 K @GLB
 D NEWINP(.INP)
 S INP(10)=9.4,INP(1)=1,DA=-1,INDDA=DA
 S CNT=0,RTN=""
 K ^UTILITY($J)
 F  S RTN=$O(^ROUTINE(RTN)) Q:RTN=""  S CNT=CNT+1,^UTILITY($J,RTN)=""
 S ^UTILITY($J,0)=CNT_";ROU",NRO=CNT
 D MAIN^ZZRGNDX(1)
 M @GLB=^UTILITY($J)
 K ^UTILITY($J)
 Q
 ;
MAIN(GLB) ;
 S:$G(GLB)="" GLB="^ZZRG"
 D CRTBASE(GLB)
 D NDXFI^ZZRGND13(GLB)
 D NDXOPT^ZZRGND13(GLB)
 D NDXRPC^ZZRGND13(GLB)
 D NDXIN^ZZRGND13(GLB,1)
 Q
 ;