ZZRGND12 ;ISC/REL,GRK - PROCESS DO, GO TO, WRITE & FOR COMMANDS ;08/05/08  13:59
 ;;7.3;TOOLKIT;**20,61,68,110,128**;Apr 25, 1995;Build 1
B(ARG,V,VADDL,POST) ;
 D E^ZZRGND1(25) 
 Q
 ;
C(ARG,V,VADDL,POST) ;
 D E^ZZRGND1(29) 
 D:ARG]"" PRCSSEXP^ZZRGND2(ARG,.V,.VADDL) 
 Q
 ;
D(ARG,V,VADDL,POST) ;
 D DG1^ZZRGND4(ARG,.V,.VADDL,"D",POST]"")
 Q
 ;
E(ARG,V,VADDL,POST) ;
 D:ARG]"" E^ZZRGND1(7),PRCSSEXP^ZZRGND2(ARG,.V,.VADDL) 
 Q
 ;
F(ARG,V,VADDL,POST) ;
 I ARG="" S IND("F")=1 Q 
 D FR^ZZRGND4(ARG,.V,.VADDL)
 Q
 ;
G(ARG,V,VADDL,POST) ;
 D DG^ZZRGND4(ARG,.V,.VADDL,"G",POST]"")
 Q
 ;
H(ARG,V,VADDL,POST) ;
 D:ARG="" E^ZZRGND1(32)
 D:ARG]"" PRCSSEXP^ZZRGND2(ARG,.V,.VADDL)
 Q
 ;
J(ARG,V,VADDL,POST) ;
 D E^ZZRGND1(36) 
 Q
 ;
K(ARG,V,VADDL,POST) ;
 D:ARG?1"(".E E^ZZRGND1(22)
 D:ARG?." " E^ZZRGND1(23)
 D KL^ZZRGND3
 D:ARG]"" PRCSSEXP^ZZRGND2(ARG,.V,.VADDL)
 Q
 ;
L(ARG,V,VADDL,POST) ;
 D LO^ZZRGND4(ARG,.V,.VADDL)
 Q
 ;
M(ARG,V,VADDL,POST) ;
 D S(ARG,.V,.VADDL)
 Q
 ;
N(ARG,V,VADDL,POST) ;
 D NE^ZZRGND3(ARG,.V,.VADDL)
 D:ARG]"" PRCSSEXP^ZZRGND2(ARG,.V,.VADDL)
 Q
 ;
O(ARG,V,VADDL,POST) ;
 D E^ZZRGND1(34)
 D O^ZZRGND3(ARG,.V,.VADDL) 
 Q
 ;
Q(ARG,V,VADDL,POST) ;
 Q:ARG=""  
 D Q^ZZRGND4
 D:ARG]"" PRCSSEXP^ZZRGND2(ARG,.V,.VADDL)
 Q  
 ;
R(ARG,V,VADDL,POST) 
 S RDTIME=0 
 D RD^ZZRGND3(ARG,.V,.VADDL)
 Q
 ;
S(ARG,V,VADDL,POST) ;
 D S^ZZRGND3(ARG,.V,.VADDL)
 Q
 ;
TR(ARG,V,VADDL,POST) ;
 D:ARG]"" PRCSSEXP^ZZRGND2(ARG,.V,.VADDL)
 Q  ;What to process. p110
 ;
U(ARG,V,VADDL,POST) ;
 S ARG=$P(ARG,":") 
 D:ARG]"" PRCSSEXP^ZZRGND2(ARG,.V,.VADDL)
 Q
 ;
V(ARG,V,VADDL,POST) ;
 D E^ZZRGND1(20)
 Q
 ;
W(ARG,V,VADDL,POST) ;
 D WR^ZZRGND4
 Q
 ;
X(ARG,V,VADDL,POST) ;
 D XE^ZZRGND4
 Q
 ;
Z(ARG,V,VADDL,POST) ;
 D E^ZZRGND1(2) 
 D ZC^ZZRGND4
 Q
 ;
 
 